"use client";

import { useEffect, useMemo, useState, type ChangeEvent, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import ArrowBackRoundedIcon from "@mui/icons-material/ArrowBackRounded";
import CloseRoundedIcon from "@mui/icons-material/CloseRounded";
import PhotoLibraryRoundedIcon from "@mui/icons-material/PhotoLibraryRounded";
import { Alert, Box, Button, Chip, Container, FormControlLabel, IconButton, MenuItem, Paper, Snackbar, Stack, Switch, TextField, Typography } from "@mui/material";
import { useAppSession } from "@/features/session/hooks/use-app-session";
import { createClient } from "@/lib/supabase/client";
import { createRoom, getRoom, updateRoom, uploadRoomImages } from "@/features/rooms/services/room-service";
import { roomAmenities, type Room } from "@/features/rooms/models/room";
import { useAppFeedback } from "@/components/providers/feedback-provider";

export function RoomForm({ roomId }: { roomId?: string }) {
  const router = useRouter(); const { session } = useAppSession(); const client = useMemo(() => createClient(), []);
  const feedback = useAppFeedback();
  const [room, setRoom] = useState<Room | null>(null); const [name, setName] = useState(""); const [roomType, setRoomType] = useState("master"); const [capacity, setCapacity] = useState(2); const [bedCount, setBedCount] = useState(1); const [price, setPrice] = useState(""); const [amenities, setAmenities] = useState<string[]>([]); const [isActive, setIsActive] = useState(true); const [files, setFiles] = useState<File[]>([]); const [existingImages, setExistingImages] = useState<string[]>([]); const [loading, setLoading] = useState(false); const [initialLoading, setInitialLoading] = useState(Boolean(roomId)); const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (!roomId || !session?.activePropertyId) return; getRoom(client, session.activePropertyId, roomId).then((value) => { if (!value) throw new Error("Room not found."); setRoom(value); setName(value.name); setRoomType(value.roomType); setCapacity(value.capacity); setBedCount(value.bedCount); setPrice(String(value.pricePerNight)); setAmenities(value.amenities); setExistingImages(value.images); setIsActive(value.isActive); }).catch((cause) => setError(cause instanceof Error ? cause.message : "Unable to load room.")).finally(() => setInitialLoading(false)); }, [client, roomId, session?.activePropertyId]);
  const previews = useMemo(() => files.map(URL.createObjectURL), [files]); useEffect(() => () => previews.forEach(URL.revokeObjectURL), [previews]);
  const pick = (event: ChangeEvent<HTMLInputElement>) => { const picked = Array.from(event.target.files ?? []); event.target.value = ""; if (existingImages.length + files.length + picked.length > 3) return setError("Maximum 3 images allowed."); if (picked.some((file) => file.size > 5 * 1024 * 1024)) return setError("Each image must be under 5 MB."); setFiles((current) => [...current, ...picked]); };
  const submit = async (event: FormEvent) => { event.preventDefault(); const propertyId = session?.activePropertyId; if (!propertyId) return setError("No active property selected."); if (name.trim().length < 2) return setError("Enter a valid room name."); const amount = Number(price); if (!amount || amount <= 0) return setError("Enter a valid room price."); if (!amenities.length) return setError("Select at least one amenity."); if (!existingImages.length && !files.length) return setError("Add at least one room image."); setLoading(true); setError(null); try { const targetId = roomId ?? crypto.randomUUID(); const uploaded = files.length ? await uploadRoomImages(client, propertyId, targetId, files) : []; const input = { name, roomType, capacity, bedCount, pricePerNight: amount, amenities, images: [...existingImages, ...uploaded], isActive }; if (roomId) await updateRoom(client, propertyId, roomId, input); else await createRoom(client, propertyId, input, targetId); feedback.success(roomId ? "Room changes saved successfully." : "Room created successfully."); router.replace(roomId ? `/rooms/${roomId}` : "/rooms"); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to save room."); } finally { setLoading(false); } };
  if (initialLoading) return <Container maxWidth="md" sx={{ py: 8 }}><Typography>Loading room…</Typography></Container>;
  return <Container component="form" onSubmit={submit} maxWidth="md" sx={{ py: { xs: 3, md: 5 } }}><Stack spacing={3}><Stack direction="row" spacing={1.5} sx={{ alignItems: "center" }}><IconButton aria-label="Back" onClick={() => router.back()}><ArrowBackRoundedIcon /></IconButton><Box><Typography variant="h4">{roomId ? `Edit ${room?.name ?? "room"}` : "Add new room"}</Typography><Typography color="text.secondary">Room details, capacity, price, amenities and images.</Typography></Box></Stack>
    <Paper variant="outlined" sx={{ p: { xs: 2.5, sm: 4 } }}><Stack spacing={2.5}><Typography variant="h6">Basic information</Typography><TextField required label="Room name / number" value={name} onChange={(e) => setName(e.target.value)} /><TextField select label="Room type" value={roomType} onChange={(e) => setRoomType(e.target.value)}>{["single","master","suite","deluxe","twin","family"].map((type) => <MenuItem key={type} value={type} sx={{ textTransform: "capitalize" }}>{type}</MenuItem>)}</TextField><Stack direction={{ xs: "column", sm: "row" }} spacing={2}><TextField fullWidth label="Guest capacity" type="number" value={capacity} onChange={(e) => setCapacity(Math.max(1, Number(e.target.value)))} slotProps={{ htmlInput: { min: 1, max: 20 } }} /><TextField fullWidth label="Bed count" type="number" value={bedCount} onChange={(e) => setBedCount(Math.max(1, Number(e.target.value)))} slotProps={{ htmlInput: { min: 1, max: 20 } }} /></Stack><TextField required label="Price per night (TZS)" type="number" value={price} onChange={(e) => setPrice(e.target.value)} slotProps={{ htmlInput: { min: 1 } }} />{roomId && <FormControlLabel control={<Switch checked={isActive} onChange={(e) => setIsActive(e.target.checked)} />} label="Room is active" />}</Stack></Paper>
    <Paper variant="outlined" sx={{ p: { xs: 2.5, sm: 4 } }}><Stack spacing={2}><Box><Typography variant="h6">Amenities</Typography><Typography color="text.secondary">Select at least one amenity.</Typography></Box><Stack direction="row" sx={{ flexWrap: "wrap", gap: 1 }}>{roomAmenities.map((item) => <Chip key={item} label={item} clickable color={amenities.includes(item) ? "primary" : "default"} variant={amenities.includes(item) ? "filled" : "outlined"} onClick={() => setAmenities((current) => current.includes(item) ? current.filter((value) => value !== item) : [...current, item])} />)}</Stack></Stack></Paper>
    <Paper variant="outlined" sx={{ p: { xs: 2.5, sm: 4 } }}><Stack spacing={2}><Box><Typography variant="h6">Room images</Typography><Typography color="text.secondary">Add up to 3 images. The first is the cover image.</Typography></Box><Stack direction="row" sx={{ flexWrap: "wrap", gap: 1.5 }}>{[...existingImages, ...previews].map((image, index) => <Box key={image} sx={{ position: "relative" }}><Box component="img" src={image} alt={`Room image ${index + 1}`} sx={{ borderRadius: 2, height: 110, objectFit: "cover", width: 140 }} /><IconButton size="small" onClick={() => index < existingImages.length ? setExistingImages((current) => current.filter((_, item) => item !== index)) : setFiles((current) => current.filter((_, item) => item !== index - existingImages.length))} sx={{ bgcolor: "rgba(0,0,0,.6)", color: "white", position: "absolute", right: 5, top: 5 }}><CloseRoundedIcon fontSize="small" /></IconButton></Box>)}{existingImages.length + files.length < 3 && <Button component="label" variant="outlined" startIcon={<PhotoLibraryRoundedIcon />} sx={{ height: 110, width: 140 }}>Add images<input hidden multiple accept="image/*" type="file" onChange={pick} /></Button>}</Stack></Stack></Paper>
    <Button type="submit" size="large" variant="contained" disabled={loading}>{loading ? "Saving room…" : roomId ? "Save changes" : "Create room"}</Button>
    <Snackbar open={Boolean(error)} autoHideDuration={6000} onClose={() => setError(null)}><Alert severity="error" variant="filled">{error}</Alert></Snackbar>
  </Stack></Container>;
}
