"use client";
import { Grid, Paper, Stack, Typography } from "@mui/material";
import HotelRoundedIcon from "@mui/icons-material/HotelRounded"; import EventAvailableRoundedIcon from "@mui/icons-material/EventAvailableRounded"; import GroupsRoundedIcon from "@mui/icons-material/GroupsRounded"; import BadgeRoundedIcon from "@mui/icons-material/BadgeRounded"; import AnalyticsRoundedIcon from "@mui/icons-material/AnalyticsRounded"; import DomainRoundedIcon from "@mui/icons-material/DomainRounded";
import { MarketingPageShell } from "@/components/content/marketing-page-shell"; import { useLanguage } from "@/components/providers/language-provider";
export default function FeaturesPage(){ const {t}=useLanguage(); const items=[
[HotelRoundedIcon,"Room management","Usimamizi wa vyumba","See room availability and operational status from one workspace.","Ona upatikanaji na hali ya vyumba kutoka sehemu moja."],
[EventAvailableRoundedIcon,"Bookings","Uhifadhi","Create, confirm, check in and check out bookings with less paperwork.","Tengeneza, thibitisha, ingiza na ondoa wageni kwa urahisi."],
[GroupsRoundedIcon,"Guest records","Taarifa za wageni","Keep useful guest and stay information organised and easy to retrieve.","Hifadhi taarifa muhimu za wageni na ukaaji kwa mpangilio."],
[BadgeRoundedIcon,"Staff & permissions","Wafanyakazi na ruhusa","Give owners, managers and reception staff the right level of access.","Wape wamiliki, mameneja na mapokezi ruhusa zinazofaa."],
[AnalyticsRoundedIcon,"Operational visibility","Mwonekano wa shughuli","Follow occupancy, arrivals, departures and daily operations at a glance.","Fuatilia matumizi ya vyumba, wanaoingia, wanaotoka na shughuli za kila siku."],
[DomainRoundedIcon,"Multiple properties","Majengo mengi","Move between properties from one account when your business grows.","Simamia majengo mengi kutoka akaunti moja biashara yako inapokua."]]; return <MarketingPageShell eyebrow={["PRODUCT FEATURES","VIPENGELE VYA BIDHAA"]} title={["Everything your property needs to stay organised.","Kila unachohitaji kuendesha biashara kwa mpangilio."]} description={["Loji Business connects rooms, bookings, guests, staff and daily property operations in one focused workspace.","Loji Business inaunganisha vyumba, uhifadhi, wageni, wafanyakazi na shughuli za kila siku katika sehemu moja."]}><Grid container spacing={2}>{items.map(([Icon,en,sw,de,ds])=><Grid size={{xs:12,md:6}} key={en as string}><Paper variant="outlined" sx={{height:"100%",p:{xs:2.5,sm:3},borderRadius:2}}><Stack spacing={2}><Icon color="primary" sx={{fontSize:32}}/><Typography variant="h5" fontWeight={750}>{t(en as string,sw as string)}</Typography><Typography color="text.secondary" lineHeight={1.75}>{t(de as string,ds as string)}</Typography></Stack></Paper></Grid>)}</Grid></MarketingPageShell> }
