"use client";
import { Grid, Paper, Stack, Typography } from "@mui/material";
import LockRoundedIcon from "@mui/icons-material/LockRounded"; import AdminPanelSettingsRoundedIcon from "@mui/icons-material/AdminPanelSettingsRounded"; import DomainVerificationRoundedIcon from "@mui/icons-material/DomainVerificationRounded"; import CloudDoneRoundedIcon from "@mui/icons-material/CloudDoneRounded";
import { MarketingPageShell } from "@/components/content/marketing-page-shell"; import { useLanguage } from "@/components/providers/language-provider";
export default function SecurityPage(){ const {t}=useLanguage(); const items=[
[LockRoundedIcon,"Authenticated access","Ufikiaji uliothibitishwa","Users access Loji Business through authenticated accounts rather than shared public links.","Watumiaji huingia Loji Business kupitia akaunti zilizothibitishwa badala ya viungo vya wazi."],
[AdminPanelSettingsRoundedIcon,"Role-based permissions","Ruhusa kulingana na jukumu","Owners and managers can control what different staff roles are allowed to see and do.","Wamiliki na mameneja wanaweza kudhibiti kile ambacho kila jukumu la mfanyakazi linaweza kuona na kufanya."],
[DomainVerificationRoundedIcon,"Property-level separation","Kutenganisha taarifa za kila jengo","Operational information is scoped to the property workspace a user is authorised to access.","Taarifa za uendeshaji huonekana ndani ya jengo ambalo mtumiaji ameruhusiwa kulifikia."],
[CloudDoneRoundedIcon,"Cloud-based service","Huduma ya wingu","Loji Business uses managed cloud infrastructure to deliver the application, storage and supporting services.","Loji Business hutumia miundombinu ya wingu kusambaza programu, hifadhi na huduma zinazohusiana."]]; return <MarketingPageShell eyebrow={["SECURITY & DATA","USALAMA NA TAARIFA"]} title={["Access controls designed around your property team.","Udhibiti wa ufikiaji unaoendana na timu ya biashara yako."]} description={["Loji Business is designed so property information is accessed through authenticated users, property membership and role permissions.","Loji Business imeundwa ili taarifa za biashara zifikikiwe kupitia watumiaji waliothibitishwa, uanachama wa jengo na ruhusa za majukumu."]}><Grid container spacing={2}>{items.map(([Icon,en,sw,de,ds])=><Grid size={{xs:12,sm:6}} key={en as string}><Paper variant="outlined" sx={{p:3,height:"100%",borderRadius:2}}><Stack spacing={1.5}><Icon color="primary" sx={{fontSize:30}}/><Typography variant="h5" fontWeight={760}>{t(en as string,sw as string)}</Typography><Typography color="text.secondary" lineHeight={1.75}>{t(de as string,ds as string)}</Typography></Stack></Paper></Grid>)}</Grid><Paper variant="outlined" sx={{mt:3,p:{xs:2.5,sm:3.5},borderRadius:2}}><Typography fontWeight={760} mb={1}>{t("Your responsibilities","Wajibu wako")}</Typography><Typography color="text.secondary" lineHeight={1.75}>{t("Property owners and authorised administrators remain responsible for choosing appropriate staff access, removing access when roles change, and handling guest and business information according to applicable requirements.","Wamiliki na wasimamizi walioidhinishwa wanaendelea kuwajibika kutoa ruhusa zinazofaa, kuondoa ruhusa majukumu yanapobadilika, na kushughulikia taarifa za wageni na biashara kwa mujibu wa masharti yanayotumika.")}</Typography></Paper></MarketingPageShell> }
